### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: '/home/zap/zap.yaml'

### ISSUE THREAD

**Issue by thinh-kieu** [previousnext/zap-orb#4]
Hi all,

How are you doing?

I've got an error when try using the OWASP ZAP scan. I attached the logs and our configs. Any suggestion to solve the error?

```
^@^@Unable to find image 'ghcr.io/zaproxy/zaproxy:stable' locally
stable: Pulling from zaproxy/zaproxy
6dce3b49cfe6: Pull complete 
b1ca0dd8a53b: Pull complete 
5dbbc599854f: Pull complete 
05e8eb1c7f5b: Pull complete 
42b9491e73f6: Pull complete 
d4da801f85b4: Pull complete 
4f4fb700ef54: Pull complete 
f474a7cc53f5: Pull complete 
b0a037e820fa: Pull complete 
f7117bedfab7: Pull complete 
7eeaaa586bb6: Pull complete 
cf0fe2776b11: Pull complete 
a5c529ea5d8b: Pull complete 
1cc78ef4cebd: Pull complete 
dd4dc89da2b5: Pull complete 
ffa97510f345: Pull complete 
af12aeac41d6: Pull complete 
50c833a08c1d: Pull complete 
f9fe109fe643: Pull complete 
ea252b13efb1: Pull complete 
Digest: sha256:1b1c5a71c7a13a1e4439bd24cc9f3f78b27760327c1cdaab86416a53495a8c63
Status: Downloaded newer image for ghcr.io/zaproxy/zaproxy:stable
Using the Automation Framework
Traceback (most recent call last):
  File "/zap/zap-baseline.py", line 662, in <module>
    main(sys.argv[1:])
  File "/zap/zap-baseline.py", line 352, in main
    with open(yaml_file, 'w') as yf:
PermissionError: [Errno 13] Permission denied: '/home/zap/zap.yaml'

Exited with code exit status 1
```

Our configs
```
version: 2.1

orbs:
  zap: pnx/zap@1.0.1

executors:
  base_with_docker:
    docker:
      - image: cimg/base:2024.11
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD

jobs:
  scecurity_scan:
    working_directory: ~/xxx
    executor: base_with_docker
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - zap/scan:
          endpoint: xxx
          slack-channel: xxx
          slack-token: $SLACK_TOKEN

workflows:
  ci:
    jobs:
      - scecurity_scan
```
